
[theme]
primaryColor = "#FFD700"
backgroundColor = "#1E90FF"
secondaryBackgroundColor = "#4169E1"
textColor = "#FFD700"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "viewer"

[logger]
level = "info"
